@startuml

object Utilisateur {
  Email: text [PK]
  MotDePasse: text
  Nom: text
  Prénom: text
  Téléphone: text
  DateCréation: datetime
  StatutCompte: {"actif", "inactif"}
}

object Candidat {

}

object Administrateur {

}

object Recruteur {
  Organisation: Organisation
}

object Organisation {
  NumeroSiren: text [PK]
  Nom: text
  Type: text
  AdresseAdministrative: text
}

object OffreEmploi {
  NumeroUnique: numeric [PK]
  Etat: {"publié", "non publié", "expiré"}
  DateValidite: datetime
  ListePieces: text
  NombrePieces: int
}

object FichePoste {
  Organisation: Organisation
  Intitule: text
  StatutPoste: text
  ResponsableHiérarchique: text
  TypeMetier: text
  LieuMission: text
  Rythme: text
  Salaire: text
  Description: text
}

object Candidature {
  DateCandidature: datetime
  PiecesDossier: files
}

Candidat <-- Utilisateur
Recruteur <-- Utilisateur
Administrateur <-- Utilisateur

Recruteur "*" -- "1" Organisation: "Emploie" <

Candidature "*" -- "1" OffreEmploi: "Recoit" <
Candidature "*" -- "1" Candidat: "Dépose" <

OffreEmploi "*" -- "1" Recruteur: "Publie" < 
OffreEmploi "*" -- "1" Organisation: "Gère" < 
OffreEmploi "*" -- "1" FichePoste: "Définit" <

Organisation "*" -- "1" Recruteur: "Soumet" < 

FichePoste "*" -- "1" Recruteur: "Rédige" <
FichePoste "*" -- "1" Organisation: "Possède" <


@enduml