name: Build and deploy Node.js app to Azure Web App - sr10project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' // Ajustez selon votre choix, peut être '18.x'

      - name: Ensure uploads directory exists
        run: mkdir -p myapp/uploads

      - name: Install dependencies
        working-directory: myapp
        run: npm install

      - name: Build and test
        working-directory: myapp
        run: |
          npm run build --if-present
          npm test

      - name: Zip artifact for deployment
        run: zip -r release.zip myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install dependencies on Azure
        run: npm install --omit=dev
        working-directory: myapp

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sr10project'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_22659E805627417681AE8A0612E17EB7 }}
          package: myapp
